/**
 * @file SpecsynLibChained.hpp
 * @author Mark Krumholz
 * @brief A spectral synthesizer that chains together several SpecsynLib libraries
 * @date 2026-07-21
 * @copyright Copyright (c) 2026 Mark Krumholz. All rights reserved.
 */

#ifndef SPECSYNLIBCHAINED_HPP
#define SPECSYNLIBCHAINED_HPP

#include "../io/SimControls.hpp"
#include "Specsyn.hpp"
#include "SpecsynCommons.hpp"
#include <array>
#include <cstddef>
#include <memory>
#include <string>
#include <utility>
#include <vector>

namespace specsyn
{

    /**
     * @class SpecsynLibChained
     * @brief A Specsyn specialization that chains together several SpecsynLib libraries
     * @details
     * Some parts of stellar parameter space are best covered by
     * different spectral libraries -- for example, an OB-star library
     * like TLUSTY for hot, massive stars, and a library like BOSZ for
     * cooler, lower-mass stars. This class lets several such libraries
     * be combined into a single Specsyn: each one is tried in turn, in
     * priority order, and the first one able to produce a spectrum for
     * a given star is used.
     *
     * Chained libraries need not share a single native wavelength
     * grid, so the constructor builds a common grid spanning all of
     * them (see makeCommonWlGrid) and resamples every library onto it
     * (see SpecsynLib::resample) before storing them.
     */
    class SpecsynLibChained : public Specsyn
    {
    public:

        /**
         * @brief Construct a SpecsynLibChained from a list of spectral libraries on disk
         * @param spectraName The names of the spectral models to chain
         *   together. Each is sorted, in the order given, into one of
         *   three per-GridType chains (see @details) according to its
         *   own registry entry -- WR_grid = true, WD_grid = true, or
         *   neither -- so within a given GridType, if a star's
         *   parameters fall within more than one of that type's own
         *   libraries' grids, the spectrum is generated by whichever
         *   one appears earliest in spectraName.
         * @param fehMin Minimum [Fe/H] value
         * @param fehMax Maximum [Fe/H] value
         * @param afe Value of [alpha/Fe]
         * @param cfe Value of [C/Fe]
         * @param microTurb Microturbulent velocity, in km/s, one entry
         *   per entry of spectraName (different libraries -- e.g. an
         *   OB-star library versus one covering cooler, lower-mass
         *   stars -- commonly assume different microturbulent
         *   velocities). An empty vector (the default) uses each
         *   library's own micro_default value from the registry
         *   instead (see SpecsynLib's constructor), rather than
         *   forcing every library in the chain to share one value.
         * @param r Spectral resolution
         * @param registryName Name of the spectral library registry file
         * @param wlMin Minimum wavelength of the output grid, in
         *   Angstrom; if 0 (the default), used together with wlMax
         *   and nWl below (see @details) as a flag to fall back on
         *   each library's own native wavelength coverage
         * @param wlMax Maximum wavelength of the output grid, in
         *   Angstrom; see wlMin
         * @param nWl Number of points in the output grid; if 0 (the
         *   default), used as a flag to fall back on each library's
         *   own native wavelength grid -- see @details
         * @param tClamp Whether classifyGridType() may ever route a
         *   star to GridType::wdGrid at all; defaults to true. See
         *   @details.
         * @throws std::runtime_error if spectraName is empty, or if
         *   microTurb is non-empty and its size does not match
         *   spectraName's
         * @details
         * Constructs one library per entry of spectraName, in order --
         * a SpecsynLibWR for an entry whose registry entry has
         * WR_grid = true, a SpecsynLibWD for an entry with
         * WD_grid = true (mutually exclusive with WR_grid), a
         * SpecsynLibNoWind for every other entry -- pairing each one
         * with the corresponding entry of microTurb (or that library's
         * own registry default, if microTurb is empty; ignored
         * entirely for a SpecsynLibWR or SpecsynLibWD entry, neither of
         * which has a microTurb axis) and otherwise using the remaining
         * arguments -- including wlMin, wlMax, and nWl -- unchanged
         * for each one. Every library, with no exception, is
         * constructed with OOBPolicy::coerce, so a star outside its
         * grid (or in one of its gaps) is still handled by that same
         * library if it has at least one valid neighboring grid point,
         * and falls through to the next library in its own chain only
         * if it truly has none -- see spec()'s own comment for what
         * happens once a star falls through its entire chain. Each is
         * upcast to (and stored as) the plain Specsyn it was
         * constructed as a SpecsynLib<OOBPolicy::coerce> specialization
         * of, since every function this class actually needs on it
         * from that point on -- spec(), specForce() -- lives on that
         * common base.
         *
         * Once every library has been loaded on its own native
         * wavelength grid, makeCommonWlGrid is used to build a single
         * grid spanning all of them, and each library is resampled
         * (see SpecsynLib::resample) onto that common grid, so that
         * every chained library's spec() output shares the same
         * length and wavelength values -- and so that wl() correctly
         * describes every one of them, not just the first. Only after
         * this are the libraries sorted into wrLibs_/wdLibs_/
         * normalLibs_, per their own already-known GridType, still in
         * their original relative order within spectraName.
         *
         * logTeffMin_/logTeffMax_/loggMin_/loggMax_ are unconditionally
         * filled with quiet_NaN() first. If tClamp is true, also scans
         * every chained library's own log(Teff) grid (via its
         * logTeff() accessor) for its minimum and maximum, storing
         * them in logTeffMin_[t]/logTeffMax_[t] (see
         * updateLogTeffRange), where t is whichever GridType that
         * library actually is (SpecsynLibWR -> wrGrid, SpecsynLibWD ->
         * wdGrid, SpecsynLibNoWind -> normalGrid) -- so a GridType with
         * no library of that kind in the chain at all is left at
         * quiet_NaN(). Likewise scans every chained SpecsynLibNoWind
         * or SpecsynLibWD library's own log(g) grid (via logg()) for
         * loggMin_[normalGrid]/loggMax_[normalGrid] and
         * loggMin_[wdGrid]/loggMax_[wdGrid] respectively --
         * GridType::wrGrid is never touched here, since Wolf-Rayet
         * atmospheres aren't parameterized by logg at all. If tClamp
         * is false, every one of these four arrays stays entirely
         * quiet_NaN(), which -- per classifyGridType's own comment --
         * means a star can never be classified GridType::wdGrid at
         * all (only GridType::wrGrid, decided independently of these
         * arrays, or GridType::normalGrid). These arrays exist purely
         * to drive that classification decision now (see spec()'s own
         * comment): unlike before this class's refactor to per-type
         * chains and specForce(), spec() itself no longer clamps a
         * star's properties into any of these ranges before
         * dispatching it.
         *
         * wnlTeffRanges_ is computed separately, and unconditionally
         * (regardless of tClamp): every chained SpecsynLibWR library's
         * own type()/logTeff() range is scanned into it, and it is then
         * handed to every one of those same libraries via their own
         * setWNLTeffRanges() -- see wnlTeffRanges_'s own comment for why
         * this, unlike the tClamp-gated arrays above, is not optional.
         * @param controls Simulation controls; forwarded unchanged to
         *   Specsyn's own constructor -- see its comment. Has no
         *   default of its own (unlike every parameter above): a
         *   reference bound to a temporary default-constructed
         *   SimControls would dangle the moment this constructor
         *   returned, since this class stores it live rather than
         *   copying out of it.
         */
        SpecsynLibChained(
            const std::vector<std::string>& spectraName,
            double fehMin,
            double fehMax,
            double afe,
            double cfe,
            const std::vector<double>& microTurb,
            double r,
            const std::string& registryName,
            double wlMin,
            double wlMax,
            std::size_t nWl,
            bool tClamp,
            const io::SimControls& controls);

        /**
         * @brief Compute a star's spectrum from whichever chain matches its own GridType
         * @param props Stellar properties, as produced by evaluating
         *   the Interpolator1D returned by Tracks2D::getIsochrone at
         *   this star's mass
         * @param feh [Fe/H] value of the star; needed because it is
         *   not carried by props itself, and not necessarily within
         *   any single chained library's own real coverage -- see this
         *   function's own @details
         * @return The star's spectrum, evaluated on the wavelength
         *   grid returned by wl(), in units of erg/s/Angstrom -- never
         *   a size-0 vector
         * @throws std::runtime_error if this star's own GridType has
         *   no chained library at all
         * @details
         * First decides which GridType this star belongs to -- see
         * classifyGridType's own comment for the exact rule (in short:
         * WR if getWRType says so; else WD if the star lies above the
         * normal grids' own coverage on log(Teff) or log(g), but the
         * WD grids' own floor still plausibly covers it on both; else
         * normal) -- and selects that GridType's own chain (wrLibs_,
         * wdLibs_, or normalLibs_).
         *
         * If (and only if) the star is normal-grid, its own log(Teff)
         * is clamped up to logTeffMin_[normalGrid] -- the coolest
         * floor among every chained normal library -- if it falls
         * below that floor, since normal libraries have no rescue of
         * their own for an out-of-range log(Teff) the way they do for
         * log(g) (see SpecsynLibNoWind::specForce()). Only the lower
         * bound is clamped: a normal-grid star exceeding the upper
         * log(Teff) bound should already have been routed to wdGrid or
         * wrGrid above, so if one still reaches here, that is a
         * genuine gap worth throwing on rather than silently clamping
         * away.
         *
         * Then tries each library in that chain, in priority order,
         * stopping at and returning the first non-empty spec() result
         * -- but unlike before this class's per-library [Fe/H]-clamp
         * fix, feh is now clamped to *that one library's own* real
         * [Fe/H] coverage (fehMin_[type][i]/fehMax_[type][i], see
         * clampFehForLibrary()) immediately before each individual
         * spec() call, not once for the whole chain: a library earlier
         * in the chain with wider coverage than a later one should
         * still see the star's own true feh if that is within its
         * reach, and a library whose own coverage doesn't reach it at
         * all should still be given its best (clamped) shot rather
         * than being skipped outright, exactly mirroring how
         * SpecsynLibNoWind::specForce() itself moves log(g) to the
         * nearest populated grid value rather than giving up. No
         * atmosphere-grid library actually has uniform coverage across
         * its own [Fe/H] range in practice (e.g. MARCS's afe=0.0
         * models stop well short of its afe=0.4 models' own reach; a
         * hot O/B star metal-poor enough to fall outside TLUSTY_O/
         * TLUSTY_B's own narrower [Fe/H] range needs the same kind of
         * rescue BOSZ/CK04/MARCS already need for other reasons) --
         * see warnIfFeHClamped()'s own comment for how this is
         * surfaced up front rather than left silent. If every library
         * in the chain still returns empty even after this clamp,
         * calls specForce() (see Specsyn's own comment) on the last
         * one, clamped to its own coverage the same way, which either
         * returns a genuine spectrum (forcing a match, e.g. by moving
         * log(g) to the nearest populated grid value -- see
         * SpecsynLibNoWind::specForce()/SpecsynLibWD::specForce()) or
         * throws for a reason other than [Fe/H] alone (e.g. log(Teff)
         * genuinely outside every chained library's own grid).
         */
        [[nodiscard]] auto spec(const StarData& props, double feh) const
        -> std::vector<double> override;

        /**
         * @brief Compute a star's spectrum for Specsyn::continuousSpecIntegrand()'s own benefit
         * @param props See spec()'s own props parameter
         * @param feh See spec()'s own feh parameter
         * @return See spec()'s own return value
         * @throws std::runtime_error under the same conditions as spec()
         * @details
         * Overrides Specsyn::specForIntegration() only to keep the
         * override itself documented and present (the base class's own
         * default already just calls spec() unchanged -- see its own
         * comment) -- now that spec() itself clamps feh per-library
         * rather than leaving normal-/WD-grid stars deliberately
         * un-rescued (see spec()'s own comment for why that distinction
         * no longer applies), there is nothing left for this override
         * to do differently, so it simply is spec().
         */
        [[nodiscard]] auto specForIntegration(const StarData& props, double feh) const
        -> std::vector<double> override;

        /**
         * @brief Build a common wavelength grid spanning several libraries' own grids
         * @param wlGrids One wavelength grid per library, each sorted
         *   ascending and non-empty
         * @return A single sorted, deduplicated wavelength grid
         *   spanning the full range covered by wlGrids
         * @throws std::runtime_error if wlGrids, or any grid in it, is empty
         * @details
         * Splits the full wavelength range into windows delineated by
         * every grid's minimum and maximum wavelength -- e.g. grids
         * covering [200, 2000] and [1500, 3000] Angstrom split the
         * range into windows [200, 1500], [1500, 2000], and
         * [2000, 3000]. Within each window, restricts to grids whose
         * own range fully contains it, and adopts whichever of those
         * has the most points there (ties favor the earlier grid in
         * wlGrids); this "fully contains" restriction matters because
         * a grid whose own range happens to end (or start) exactly at
         * one edge of a window still has that one boundary point
         * technically inside it, which could otherwise spuriously tie
         * against (or even beat) another grid that actually spans the
         * window. If no grid fully contains a window, falls back to
         * whichever grid simply has the most points physically
         * present there, so a grid's own trailing edge point is still
         * kept when nothing else reaches anywhere near it; a window
         * with no points from any grid at all (a genuine coverage gap)
         * contributes nothing to the result, rather than inventing
         * samples there. The result is these per-window selections
         * concatenated in order, so it is itself sorted and spans the
         * union of every input grid's range wherever that union has no
         * gaps.
         *
         * This is a general-purpose grid-merging utility, not tied to
         * SpecsynLibChained's own constructor use of it (which passes
         * the wl() of each of its chained libraries), so it takes
         * wavelength grids directly rather than Specsyn/SpecsynLib
         * objects.
         */
        [[nodiscard]] static auto makeCommonWlGrid(
            const std::vector<std::vector<double>>& wlGrids) -> std::vector<double>;

    private:

        /**
         * @brief Hand wnlTeffRanges_ down to every chained SpecsynLibWR library's own copy
         * @details
         * Factored out of the constructor purely to keep its own
         * cognitive complexity down. Called once, after wnlTeffRanges_
         * has been fully computed and wrLibs_ populated -- see
         * wnlTeffRanges_'s own comment for why every chained
         * SpecsynLibWR library needs its own copy of the same combined
         * range data classifyGridType uses.
         */
        void propagateWNLTeffRanges();

        /**
         * @brief Set fehMin_/fehMax_/libNames_ from every chained library, individually
         * @details
         * Factored out of the constructor purely to keep its own
         * cognitive complexity down -- see propagateWNLTeffRanges()'s
         * own identical rationale. Called once, after wrLibs_/wdLibs_/
         * normalLibs_ have all been fully populated -- see fehMin_'s
         * own comment for exactly what this computes and why.
         */
        void updateFeHRanges();

        /**
         * @brief Return the [Fe/H] to actually query library i of type's own chain with
         * @param feh The star's own true [Fe/H]
         * @param type The GridType whose chain library i belongs to
         * @param libIdx Index into chainFor(type) (and fehMin_[type]/
         *   fehMax_[type]/libNames_[type], which all share that same
         *   per-library indexing)
         * @return feh, clamped into
         *   [fehMin_[type][libIdx], fehMax_[type][libIdx]] -- unchanged
         *   on whichever side is quiet_NaN() (a library with no [Fe/H]
         *   axis at all, i.e. SpecsynLibWD)
         * @details
         * Factored out of spec() purely so both the ordinary per-
         * library dispatch loop and its final specForce() fallback can
         * share one place to compute this -- see spec()'s own comment
         * for why the clamp is per-library rather than once for the
         * whole chain.
         */
        [[nodiscard]] auto clampFehForLibrary(double feh, GridType type, std::size_t libIdx) const -> double;

        /**
         * @brief Warn for every chained library whose own [Fe/H] coverage the requested range exceeds
         * @param fehMin Minimum [Fe/H] this SpecsynLibChained was constructed to cover
         * @param fehMax Maximum [Fe/H] this SpecsynLibChained was constructed to cover
         * @details
         * Factored out of the constructor purely to keep its own
         * cognitive complexity down -- see propagateWNLTeffRanges()'s
         * own identical rationale. Called once, after updateFeHRanges()
         * has populated fehMin_/fehMax_/libNames_. Loops over every
         * library of every GridType (chainFor(wrGrid) +
         * chainFor(wdGrid) + chainFor(normalGrid), in that per-type
         * chain order); a library with no [Fe/H] axis at all
         * (fehMin_[type][i] left at quiet_NaN() by updateFeHRanges(),
         * i.e. any SpecsynLibWD) is skipped, since there is nothing to
         * clamp. For every other library whose own real [Fe/H]
         * coverage does not fully contain [fehMin, fehMax], prints one
         * warning naming that specific library -- since spec() now
         * clamps feh to *that* library's own coverage individually
         * before ever calling it (see spec()'s own comment), any star
         * landing in the excluded portion when that library is tried
         * is silently clamped to its nearest available [Fe/H] rather
         * than being skipped or throwing; this surfaces that up front,
         * library by library, mirroring the warning
         * SpecsynLibNoWind's own afe-nudge rescue prints for its
         * analogous [Fe/H]-coverage gap. A library whose own coverage
         * already fully contains [fehMin, fehMax] is silent, exactly
         * as before this per-library generalization for the single
         * chained WR library that used to be the only case checked.
         */
        void warnIfFeHClamped(double fehMin, double fehMax) const;

        /**
         * @brief Return whichever of wrLibs_/wdLibs_/normalLibs_ matches type
         * @param type The GridType to look up
         * @return A const reference to that GridType's own chain
         * @details
         * Factored out of spec() purely so it has one place to consult
         * rather than repeating the same three-way branch wherever a
         * GridType needs to be turned into its own chain.
         */
        [[nodiscard]] auto chainFor(GridType type) const -> const std::vector<std::unique_ptr<Specsyn>>&;

        /**
         * @brief Clamp a normal-grid star's own log(Teff) up to the chain's combined lower floor, if needed
         * @param props Stellar properties to (possibly) adjust; passed
         *   by value, so the caller's own copy is never modified
         * @param type The GridType props was already classified as
         * @return props, with its own log(Teff) entry raised to
         *   logTeffMin_[normalGrid] if type is GridType::normalGrid
         *   and it was below that floor; unchanged for every other
         *   GridType, or if it was already at or above the floor
         * @details
         * Shared by both spec() and specForIntegration() -- see
         * spec()'s own comment for the full rationale (in short: no
         * rescue of its own exists for an out-of-range log(Teff), the
         * way SpecsynLibNoWind::specForce() has for log(g), and this
         * is deliberately one-sided -- only the lower bound is
         * clamped, since a star exceeding the upper bound should
         * already have been routed to wdGrid/wrGrid by
         * classifyGridType(), and if it wasn't, that's a real gap
         * worth throwing on rather than silently clamping away).
         */
        [[nodiscard]] auto clampNormalLogTeffFloor(StarData props, GridType type) const -> StarData;

        /**
         * @brief The chained Wolf-Rayet (GridType::wrGrid) libraries, in priority order
         * @details
         * Every entry of the constructor's own spectraName whose
         * registry entry has WR_grid = true, in their original
         * relative order, each a SpecsynLibWR<OOBPolicy::coerce>
         * upcast to (and stored as) the polymorphic Specsyn base --
         * see the constructor's own comment for why every chained
         * library, regardless of GridType, is now built with
         * OOBPolicy::coerce alone.
         */
        std::vector<std::unique_ptr<Specsyn>> wrLibs_;

        /**
         * @brief The chained white dwarf (GridType::wdGrid) libraries, in priority order
         * @details
         * Every entry of the constructor's own spectraName whose
         * registry entry has WD_grid = true, in their original
         * relative order -- see wrLibs_'s own comment, which applies
         * here identically except for GridType.
         */
        std::vector<std::unique_ptr<Specsyn>> wdLibs_;

        /**
         * @brief The chained ordinary-star (GridType::normalGrid) libraries, in priority order
         * @details
         * Every entry of the constructor's own spectraName with
         * neither WR_grid nor WD_grid set, in their original relative
         * order -- see wrLibs_'s own comment, which applies here
         * identically except for GridType.
         */
        std::vector<std::unique_ptr<Specsyn>> normalLibs_;

        /**
         * @brief Number of real GridType enumerators, used to size the arrays below
         */
        static constexpr std::size_t nGridType = static_cast<std::size_t>(GridType::nGridType);

        /**
         * @brief The log(Teff) range spanned by each kind of chained library, indexed by GridType
         * @details
         * Filled with quiet_NaN() unconditionally at the top of the
         * constructor; if the constructor's tClamp argument is true,
         * entries are then overwritten (via updateLogTeffRange) with
         * the minimum/maximum of every chained library's own logTeff()
         * grid, indexed by which kind of library it is (GridType::
         * wrGrid/wdGrid/normalGrid) -- so, unlike before, a WR-type
         * star's clamp no longer shares a single combined range with
         * WD- or normal-type stars. A GridType with no library of that
         * kind actually present in the chain is left at quiet_NaN().
         * See the constructor's and spec()'s own comments.
         */
        std::array<double, nGridType> logTeffMin_;
        std::array<double, nGridType> logTeffMax_; /**< See logTeffMin_ */

        /**
         * @brief The log(g) range spanned by each kind of chained library, indexed by GridType
         * @details
         * Filled with quiet_NaN() unconditionally at the top of the
         * constructor; if the constructor's tClamp argument is true,
         * entries are then overwritten (via updateLoggRange) with the
         * minimum/maximum of every chained SpecsynLibNoWind/SpecsynLibWD
         * library's own logg() grid, indexed by GridType::normalGrid/
         * wdGrid respectively -- GridType::wrGrid is never touched
         * here, since Wolf-Rayet atmospheres aren't parameterized by
         * logg at all (see the constructor's own comment). See the
         * constructor's and spec()'s own comments.
         */
        std::array<double, nGridType> loggMin_;
        std::array<double, nGridType> loggMax_; /**< See loggMin_ */

        /**
         * @brief The [min, max] log(Teff) range spanned by each of the three chained WNL buckets
         * @details
         * Index 0 is WNLH20's own range, 1 is WNLH40's, 2 is WNLH60's --
         * see SpecsynLibWR::getWRType's own wnlTeffRanges parameter, which
         * this is passed to (from classifyGridType, via spec()) unconditionally,
         * regardless of tClamp -- unlike logTeffMin_/logTeffMax_/loggMin_/
         * loggMax_, this isn't an optional coercion clamp, but data
         * classifyGridType needs to correctly tell a genuine WNL star
         * apart from an ordinary star whose surface composition merely
         * resembles one (see getWRType's own comment for why). Computed
         * once, unconditionally, in the constructor by scanning every
         * chained SpecsynLibWR library's own type()/logTeff(), and also
         * handed to each of those same libraries via their own
         * setWNLTeffRanges(), so wrLibs_'s own spec() calls agree with
         * classifyGridType's decision about which star is which WRType.
         * An index whose bucket has no chained library at all is left at
         * {quiet_NaN(), quiet_NaN()}.
         */
        std::array<std::pair<double, double>, 3> wnlTeffRanges_;

        /**
         * @brief The [Fe/H] range of each individual chained library, indexed by GridType then chain position
         * @details
         * Each of the nGridType entries starts as an empty vector
         * (there being no meaningful "unconditional" fill value for a
         * not-yet-known chain length, unlike logTeffMin_/logTeffMax_/
         * loggMin_/loggMax_ above), then unconditionally (regardless of
         * tClamp -- this is a correctness fix, not an optional
         * coercion clamp) resized and filled by updateFeHRanges(),
         * once wrLibs_/wdLibs_/normalLibs_ are populated, to
         * chainFor(type).size() entries: fehMin_[type][i]/
         * fehMax_[type][i] hold chainFor(type)[i]'s own fehMin()/
         * fehMax(), i.e. libNames_[type][i]'s own real coverage. An
         * entry is left at quiet_NaN() if that specific library has no
         * [Fe/H] axis at all (SpecsynLibWD; its base-class fehMin()/
         * fehMax() are the unrestricted -infinity/+infinity, not
         * copied through here, per the same "only finite bounds count"
         * rule fehMin()'s own comment describes).
         *
         * Deliberately per-library, not a single value per GridType
         * (as an earlier version of this fix used, taken from
         * whichever library was chainFor(type).back()): different
         * libraries chained under the same GridType commonly have
         * genuinely different [Fe/H] reach from one another (e.g.
         * TLUSTY_O/TLUSTY_B's own [Fe/H] range is narrower than BOSZ/
         * CK04/MARCS's, all four still normalGrid), so a single
         * combined value -- whether the narrowest, the widest, or
         * chain.back()'s own -- would either clamp a star too
         * aggressively for an earlier library that could have covered
         * it unclamped, or not aggressively enough for a later one
         * that can't. See spec()'s own comment for how this is used:
         * a star's feh is clamped to *that specific library's own*
         * fehMin_[type][i]/fehMax_[type][i] immediately before each
         * individual library in the chain is tried, not once for the
         * whole chain.
         */
        std::array<std::vector<double>, nGridType> fehMin_;
        std::array<std::vector<double>, nGridType> fehMax_; /**< See fehMin_ */

        /**
         * @brief The registry name of each individual chained library, indexed the same way as fehMin_/fehMax_
         * @details
         * Filled alongside wrLibs_/wdLibs_/normalLibs_ themselves, in
         * the constructor's own sort of allLibs into those three
         * chains -- libNames_[type][i] is chainFor(type)[i]'s own
         * spectraName entry, purely so warnIfFeHClamped() can name a
         * specific library in its warning rather than only saying
         * "the chained WR library" generically, as the single-library
         * WR-only version of that check used to.
         */
        std::array<std::vector<std::string>, nGridType> libNames_;
    };

} // namespace specsyn

#endif // SPECSYNLIBCHAINED_HPP
