/**
 * @file SpecsynLibChained.hpp
 * @author Mark Krumholz
 * @brief A spectral synthesizer that chains together several SpecsynLib libraries
 * @date 2026-07-21
 */

#ifndef SPECSYNLIBCHAINED_HPP
#define SPECSYNLIBCHAINED_HPP

#include "../tracks/TrackCommons.hpp"
#include "Specsyn.hpp"
#include "SpecsynCommons.hpp"
#include <memory>
#include <string>
#include <vector>

namespace specsyn
{

    /**
     * @class SpecsynLibChained
     * @brief A Specsyn specialization that chains together several SpecsynLib libraries
     * @details
     * Some parts of stellar parameter space are best covered by
     * different spectral libraries -- for example, an OB-star library
     * like TLUSTY for hot, massive stars, and a library like BOSZ for
     * cooler, lower-mass stars. This class lets several such libraries
     * be combined into a single Specsyn: each one is tried in turn, in
     * priority order, and the first one able to produce a spectrum for
     * a given star is used.
     */
    class SpecsynLibChained : public Specsyn
    {
    public:

        /**
         * @brief Construct a SpecsynLibChained from a list of spectral libraries on disk
         * @param spectraName The names of the spectral models to chain
         *   together, in priority order: if a star's parameters fall
         *   within more than one of these libraries' grids, the
         *   spectrum is generated by whichever one appears earliest in
         *   this list
         * @param fehMin Minimum [Fe/H] value
         * @param fehMax Maximum [Fe/H] value
         * @param afe Value of [alpha/Fe]
         * @param cfe Value of [C/Fe]
         * @param microTurb Microturbulent velocity, in km/s, one entry
         *   per entry of spectraName (different libraries -- e.g. an
         *   OB-star library versus one covering cooler, lower-mass
         *   stars -- commonly assume different microturbulent
         *   velocities). An empty vector (the default) uses
         *   defaultMicroTurb for every library in the chain.
         * @param r Spectral resolution
         * @param registryName Name of the spectral library registry file
         * @param z The redshift; defaults to zero
         * @throws std::runtime_error if spectraName is empty, or if
         *   microTurb is non-empty and its size does not match
         *   spectraName's
         * @details
         * Constructs one SpecsynLib per entry of spectraName, in
         * order, pairing each one with the corresponding entry of
         * microTurb (or defaultMicroTurb, if microTurb is empty) and
         * otherwise using the remaining arguments unchanged for each
         * one. Every library but the last is constructed with
         * OOBPolicy::silent, so that a star outside its grid simply
         * falls through to the next library in the chain; the last
         * library is constructed with OOBPolicy::Throw, so that a star
         * outside every library's grid still produces an error rather
         * than silently vanishing.
         */
        SpecsynLibChained(
            const std::vector<std::string>& spectraName,
            double fehMin,
            double fehMax,
            double afe = tracks::defaultAFe,
            double cfe = defaultCFe,
            const std::vector<double>& microTurb = {},
            double r = defaultR,
            const std::string& registryName = defaultRegistry,
            double z = 0.0);

        /**
         * @brief Compute a star's spectrum by trying each chained library in turn
         * @param props Stellar properties, as produced by evaluating
         *   the Interpolator1D returned by Tracks2D::getIsochrone at
         *   this star's mass
         * @param feh [Fe/H] value of the star; needed because it is
         *   not carried by props itself
         * @return The star's spectrum, evaluated on the wavelength
         *   grid returned by wl(), in units of erg/s/Angstrom, as
         *   produced by the first chained library able to generate one
         * @throws std::runtime_error if the star falls outside every
         *   chained library's grid
         * @details
         * Calls spec() on each library in the chain in priority order,
         * stopping at and returning the first non-empty result. The
         * last library in the chain is constructed with
         * OOBPolicy::Throw, so if every earlier library returns an
         * empty (out-of-bounds) result, this call throws rather than
         * returning silently.
         */
        [[nodiscard]] auto spec(const StarData& props, double feh) const
        -> std::vector<double> override;

    private:

        /**
         * @brief The chained libraries, in priority order
         * @details
         * Stored as pointers to the polymorphic Specsyn base, rather
         * than as SpecsynLib values directly, because each library's
         * OOBPolicy is a compile-time template parameter -- the
         * silent-policy libraries earlier in the chain and the
         * throw-policy library at its end are genuinely different
         * types, and only differ in which OOBPolicy they were built
         * with.
         */
        std::vector<std::unique_ptr<Specsyn>> libs_;
    };

} // namespace specsyn

#endif // SPECSYNLIBCHAINED_HPP
